### ISSUE TITLE
'state' post variable not found - woocommerce-creditcard v3.0 & v3.1.0

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/Paytabs-e-commerce-plugins#11]
Hi @paytabscom @SamySaad @walsammak and @Jasmine-paytabs,
I want to report a bug in your old and new WooCommerce plugin.
When I choose Kuwait, Bahrain or UAE in checkout page, the state field is hidden in Woocommerce because these countries don't use states in their address.
The problem is that your plugin shows this error ( 'state' post variable not found ).
Please don't make the state field required.
A lot of my customers from these countries failed to pay via PayTabs because of this error.
Please make it a high priority.
Thanks.

**Comment by paytabscom** [comment]
Hi @ihelpco 
Can you please try the latest plugin, it is been moved to separate branch now.

https://github.com/paytabscom/paytabs-woocommerce

The fix for the mentioned issue will be pushed soonest on the above repository.
