### ISSUE TITLE
paytabs-magneto-v2.x-express-checkout not working on M2.3

### ISSUE THREAD

**Issue by hassanas** [paytabscom/Paytabs-e-commerce-plugins#2]
extension version is:
`<module name="Paytabs_Paytabsexpress" setup_version="2.1.0">`
when we click on place order it just do nothing button disabled. not diverted for payments & order placed with pending payment.
No error in console

**Comment by interequipment** [comment]
Having same issue on Magento 2.3.1

**Comment by syedsaleem086** [comment]
Having the same issue on Magento 2.3.2 @paytabscom any update

**Comment by syedsaleem086** [comment]
@paytabscom any update? :(

**Comment by darkshadow93** [comment]
I also having same issue. Kindly update

**Comment by darkshadow93** [comment]
Hii guys...i tried this and just uncomment the line(no. 253) "return $html . $js;" of PaymentMethod.php in Model folder and it's working now.
