### ISSUE TITLE
WHMCS payment gateway

### ISSUE THREAD

**Issue by mshannaq** [paytabscom/Paytabs-e-commerce-plugins#3]
Hello

are you sure from the WHMCS payment gateway is stable for the current version of WHMCS  version 7.8.3

after activating the paytabs payment gateway from WHMCS payment gateway options and then try to pay any invoice using the payment gateway it do nothing

it just show pay now 

https://prnt.sc/plk2lx

and when clicking on pay now button it shown another page with pay now link again see

http://prntscr.com/plk4m4

http://prntscr.com/plk50s

so what do you think?

**Comment by paytabscom** [comment]
Hi @mshannaq 

Please check our latest WHMCS plugin, supporting the latest version 7.9
https://github.com/paytabscom/paytabs-whmcs
