### ISSUE TITLE
Magnto Version 2.2.4 paytabsexpress/ipn/callback/ does dont get the post data

### ISSUE THREAD

**Issue by RasikMiyani** [paytabscom/Paytabs-e-commerce-plugins#5]
**when I have place the order using paytabsexpress extension than that order transation at the paytabs   give done.but magento side going to _failure why?**

I have dedug the paytabsexpress extension why alway going 400 

```
public function execute()
echo "<pre>";
print_r($postdata = $this->request->getPost());
die();
    {
        try {
            // Cryptographically verify authenticity of callback
            if($this->getRequest()->isPost())
			{				
				$this->_success();
				$this->paymentAction();
			}
			else
			{
	            $this->_logger->addError("Paytabs: no post back data received in callback");
				return $this->_failure();
			}
        } catch (Exception $e) {
            $this->_logger->addError("Paytabs: error processing callback");
            $this->_logger->addError($e->getMessage());
            return $this->_failure();
        }
```

I have check posted transaction data but that was give the blank array and goint to the failure in magento side.

**Expected Result :** 
             Place order at magento site and order suceesfully redirect to the order sucess page.

**Comment by paytabscom** [comment]
Hi @RasikMiyani 

Please check our latest version of Magento for Magneto 2.3
https://github.com/paytabscom/Paytabs-e-commerce-plugins/tree/master/Magento
